# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=200)),
                ('src_root', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
            ],
        ),
    ]
