# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='src',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
