# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0002_auto_20170119_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='file_type',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='src_root',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
