# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0003_auto_20170119_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='src',
        ),
    ]
