# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0004_remove_pattern_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
