# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0005_auto_20170119_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='grid',
            new_name='cells',
        ),
    ]
