# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0006_auto_20170130_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='columns',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='rows',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
