# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_life', '0007_auto_20170131_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
